### ISSUE TITLE
Apollo from command line & Chrome extension

### ISSUE THREAD

**Issue by dborowiec10** [amirgamil/apollo#4]
First of all, amazing project! Really clever way of sifting through search results like that.
I was wondering if you thought about cmdline client for apollo?
I spend quite a lot of time in my terminal and have to context switch to browser if i need something.
Tmuxing into apollo would be really useful in my case, especially for code documentation or papers I've read.

Might be material for another feature request / idea but having a Chrome / Firefox extension to quickly pull webpages into personal store for apollo as you read them would be very cool. I often read something, leave it in the 200 Chrome tabs I have open and need to find it 2 days later and find myself digging through my history. So far I've tried things like Workona to categorise tabs into projects, but its tedious and I can see Apollo being much less attention hungry than that.

**Comment by amirgamil** [comment]
Hi! Thank you!
As of right now, I have not. But if you wanted to create your own client, the backend code would basically stay the same, so you'd only have to add the CLI logic. 

As for the chrome extension, I would love something like that! I was actually planning on shipping the project with a chrome extension to do a similar logic, but thought it would be better to start simple. A possible solution could be keeping a bookmarked library and using something like Zotero to download the bookmared websites locally, then you could pull the data in as a data source. 

I may or may not add a chrome extension in the future but if anyone would like to do it, feel free to submit a PR!

**Comment by dborowiec10** [comment]
Hi @amirgamil. I will be closing this issue as it seems it could be split into 2 separate PRs instead and I have no further questions regarding the above.
I will also be submitting a PR for the Chrome extension so I'd appreciate if you can have a look (it will be a submodule to my own repo) and accept/review.

Cheers!
