### ISSUE TITLE
[suggestion/enhancement] Use pandoc

### ISSUE THREAD

**Issue by pcause** [amirgamil/apollo#9]
You use youtube-dl to get subtitles for videos.  For local files and things like PDF's and other form's that might get downloaded, pandoc will convert just about anything to txt.  Perhaps if you check in the crawler for file:// and then use pandoc to get the file as text which you can index a lot more options open up.  I suspect a lot of people have local files/content they want to add to apollo and this would give huge flexibility.

**Comment by amirgamil** [comment]
That sounds like an awesome idea! If you'd like to submit a PR, please do!
